# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test the application"
  lane :test_app do
    # run tests
    scan
  end

  desc "test and change log message"
  lane :testandlog do
    # run tests
    test_app
    # change log message
    change_log_message = changelog_from_git_commits(commits_count:1)
  end
end

platform :ios do
  desc "Build the application"
  lane :build do
    # build app
    gym
  end
end
